export default [
  {nome: 'Cura', custo:1},
  {nome: 'Espelho', custo:3},
  {nome: 'Espírito de Gelo', custo:1},
  {nome: 'Esqueletos', custo:1},
  {nome: 'Bola de Neve', custo:2},
  {nome: 'Destruidores de Muros', custo:2},
  {nome: 'Morcegos', custo:2},
  {nome: 'Barril de Bárbaro', custo:2},
  {nome: 'Fúria', custo:2},
  {nome: 'Espíritos de Fogo', custo:2},
  {nome: 'Goblins', custo:2},
  {nome: 'Goblins Lanceiros', custo:2},
  {nome: 'Terremoto', custo:3},
  {nome: 'Servos', custo:3},
  {nome: 'Arqueiras', custo:3},
  {nome: 'Clone', custo:3},
  {nome: 'Barril de Esqueletos', custo:3},
  {nome: 'Tornado', custo:3},
  {nome: 'Mago de Gelo', custo:3},
  {nome: 'Canhão', custo:3},
  {nome: 'Guardas', custo:3},
  {nome: 'Fantasma Real', custo:3},
  {nome: 'Lápide', custo:3},
  {nome: 'Bandida', custo:3},
  {nome: 'Barril de Goblin', custo:3},
  {nome: 'Bombardeiro', custo:3},
  {nome: 'Mineiro', custo:3},
  {nome: 'Gangue de Goblins', custo:3},
  {nome: 'Flechas', custo:3},
  {nome: 'Goblin com Dardo', custo:3},
  {nome: 'Megasservo', custo:3},
  {nome: 'Golem de Elixir', custo:3},
  {nome: 'Dragão Infernal', custo:4},
  {nome: 'Aríete de Batalha', custo:4},
  {nome: 'Lenhador', custo:4},
  {nome: 'Valquíria', custo:4},
  {nome: 'Bola de Fogo', custo:4},
  {nome: 'Caçador', custo:4},
  {nome: 'Jaula de Goblin', custo:4},
  {nome: 'Gelo', custo:4},
  {nome: 'Fornalha', custo:4},
  {nome: 'Mosqueteira', custo:4},
  {nome: 'Príncipe das Trevas', custo:4},
  {nome: 'Tesla', custo:4},
  {nome: 'Eletrocutadores', custo:4},
  {nome: 'Torre de Bombas', custo:4},
  {nome: 'Morteiro', custo:4},
  {nome: 'Veneno', custo:4},
  {nome: 'Corredor', custo:4},
  {nome: 'Máquina Voadora', custo:4},
  {nome: 'Bebê Dragão', custo:4},
  {nome: 'Mini P.E.K.K.A', custo:4},
  {nome: 'Bruxa', custo:5},
  {nome: 'Dragão Elétrico', custo:5},
  {nome: 'Porcos Reais', custo:5},
  {nome: 'Cabana de Goblins', custo:5},
  {nome: 'Carrinho de Canhão', custo:5},
  {nome: 'Torre Inferno', custo:5},
  {nome: 'Patifes', custo:5},
  {nome: 'Balão', custo:5},
  {nome: 'Executor', custo:5},
  {nome: 'Lançador', custo:5},
  {nome: 'Gigante', custo:5},
  {nome: 'Cemitério', custo:5},
  {nome: 'Horda de Servos', custo:5},
  {nome: 'Príncipe', custo:5},
  {nome: 'Bárbaros', custo:5},
  {nome: 'Domadora de Carneiro', custo:5},
  {nome: 'Goblin Gigante', custo:6},
  {nome: 'Coletor de Elixir', custo:6},
  {nome: 'X-Besta', custo:6},
  {nome: 'Gigante Real', custo:6},
  {nome: 'Esqueleto Gigante', custo:6},
  {nome: 'Megacavaleiro', custo:7},
  {nome: 'Cabana de Bárbaros', custo:7},
  {nome: 'Recrutas Reais', custo:7},
  {nome: 'Lava Hound', custo:7},
  {nome: 'Golem', custo:8},
  {nome: 'Três Mosqueteiras', custo:9},
  {nome: 'Pescador', custo:3},
  {nome: 'Bruxa Sombria', custo:4},
  {nome: 'Arqueiro Mágico', custo:4},
  {nome: 'P.E.K.K.A', custo:7},
  {nome: 'Mago', custo:5},
  {nome: 'Cavaleiro', custo:3},
  {nome: 'O Tronco', custo:2},
  {nome: 'Exército de Esqueletos', custo:3},
  {nome: 'Princesa', custo:3},
  {nome: 'Mago Elétrico', custo:4},
  {nome: 'Zap', custo:2}
].map(e => ({...e, img: require(`./media/cards/${makeImgName(e.nome)}Card.png`)}))