export default [
  { name: 'Archers', elixir_cost: 3 },
  { name: 'Baby Dragon', elixir_cost: 4 },
  { name: 'Balloon', elixir_coCommonst: 5 },
  { name: 'Bandit', elixir_cost: 3 },
  { name: 'Barbarians', elixir_cost: 5 },
  { name: 'Bats', elixir_cost: 2 },
  { name: 'Battle Ram', elixir_cost: 4 },
  { name: 'Bomber', elixir_cost: 3 },
  { name: 'Bowler', elixir_cost: 5 },
  { name: 'Cannon Cart', elixir_cost: 5 },
  { name: 'Dark Prince', elixir_cost: 4 },
  { name: 'Dart Goblin', elixir_cost: 3 },
  { name: 'Electro Dragon', elixir_cost: 5 },
  { name: 'Electro Wizard', elixir_cost: 4 },
  { name: 'Elite Barbarians', elixir_cost: 6 },
  { name: 'Elixir Golem', elixir_cost: 3 },
  { name: 'Executioner', elixir_cost: 5 },
  { name: 'Fire Spirits', elixir_cost: 2 },
  { name: 'Fisherman', elixir_cost: 3 },
  { name: 'Flying Machine', elixir_cost: 4 },
  { name: 'Giant', elixir_cost: 5 },
  { name: 'Giant Skeleton', elixir_cost: 6 },
  { name: 'Goblin Gang', elixir_cost: 3 },
  { name: 'Goblin Giant', elixir_cost: 6 },
  { name: 'Goblins', elixir_cost: 2 },
  { name: 'Golem', elixir_cost: 8 },
  { name: 'Guards', elixir_cost: 3 },
  { name: 'Hog Rider', elixir_cost: 4 },
  { name: 'Hunter', elixir_cost: 4 },
  { name: 'Ice Golem', elixir_cost: 2 },
  { name: 'Ice Spirit', elixir_cost: 1 },
  { name: 'Ice Wizard', elixir_cost: 3 },
  { name: 'Inferno Dragon', elixir_cost: 4 },
  { name: 'Knight', elixir_cost: 3 },
  { name: 'Lava Hound', elixir_cost: 7 },
  { name: 'Lumberjack', elixir_cost: 4 },
  { name: 'Magic Archer', elixir_cost: 4 },
  { name: 'Mega Knight', elixir_cost: 7 },
  { name: 'Mega Minion', elixir_cost: 3 },
  { name: 'Mini P.E.K.K.A.', elixir_cost: 4 },
  { name: 'Miner', elixir_cost: 3 },
  { name: 'Minions', elixir_cost: 3 },
  { name: 'Minion Horde', elixir_cost: 5 },
  { name: 'Musketeer', elixir_cost: 4 },
  { name: 'Night Witch', elixir_cost: 4 },
  { name: 'P.E.K.K.A.', elixir_cost: 7 },
  { name: 'Prince', elixir_cost: 5 },
  { name: 'Princess', elixir_cost: 3 },
  { name: 'Ram Rider', elixir_cost: 5 },
  { name: 'Rascals', elixir_cost: 5 },
  { name: 'Royal Ghost', elixir_cost: 3 },
  { name: 'Royal Giant', elixir_cost: 6 },
  { name: 'Royal Hogs', elixir_cost: 5 },
  { name: 'Royal Recruits', elixir_cost: 7 },
  { name: 'Skeletons', elixir_cost: 1 },
  { name: 'Skeleton Army', elixir_cost: 3 },
  { name: 'Skeleton Barrel', elixir_cost: 3 },
  { name: 'Sparky', elixir_cost: 6 },
  { name: 'Spear Goblins', elixir_cost: 2 },
  { name: 'Three Musketeers', elixir_cost: 9 },
  { name: 'Valkyrie', elixir_cost: 4 },
  { name: 'Wall Breakers', elixir_cost: 2 },
  { name: 'Witch', elixir_cost: 5 },
  { name: 'Wizard', elixir_cost: 5 },
  { name: 'Zappies', elixir_cost: 4 },
  
  { name: 'Bomb Tower', elixir_cost: 4 },
  { name: 'Cannon', elixir_cost: 3 },
  { name: 'Inferno Tower', elixir_cost: 5 },
  { name: 'Mortar', elixir_cost: 4 },
  { name: 'Tesla', elixir_cost: 4 },
  { name: 'X-Bow', elixir_cost: 6 },
  
  { name: 'Barbarian Hut', elixir_cost: 7 },
  { name: 'Elixir Collector', elixir_cost: 6 },
  { name: 'Furnace', elixir_cost: 4 },
  { name: 'Goblin Hut', elixir_cost: 3 },
  { name: 'Goblin Cage', elixir_cost: 4 },
  { name: 'Tombstone', elixir_cost: 3 },
  
  { name: 'Arrows', elixir_cost: 3 },
  { name: 'Barbarian Barrel', elixir_cost: 2 },
  { name: 'Goblin Barrel', elixir_cost: 3 },
  { name: 'Earthquake', elixir_cost: 3 },
  { name: 'Fireball', elixir_cost: 4 },
  { name: 'Freeze', elixir_cost: 4 },
  { name: 'Giant Snowball', elixir_cost: 2 },
  { name: 'Lightning', elixir_cost: 6 },
  { name: 'Poison', elixir_cost: 4 },
  { name: 'Rocket', elixir_cost: 6 },
  { name: 'The Log', elixir_cost: 2 },
  { name: 'Tornado', elixir_cost: 3 },
  { name: 'Zap', elixir_cost: 2 },
  
  { name: 'Clone', elixir_cost: 3 },
  { name: 'Heal', elixir_cost: 1 },
  { name: 'Mirror', elixir_cost: 3 },
  { name: 'Rage', elixir_cost: 2 },
  { name: 'Graveyard', elixir_cost: 5 }
].map(e => ({ ...e, img: require(`./media/cards/${e.name}.png`).default }))