-- MySQL Script generated by MySQL Workbench
-- sáb 14 dez 2019 22:49:55 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CLASHROYALE
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CLASHROYALE` ;

-- -----------------------------------------------------
-- Schema CLASHROYALE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CLASHROYALE` DEFAULT CHARACTER SET latin1 ;
USE `CLASHROYALE` ;

-- -----------------------------------------------------
-- Table `CLASHROYALE`.`cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CLASHROYALE`.`cards` ;

CREATE TABLE IF NOT EXISTS `CLASHROYALE`.`cards` (
  `card_number` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `rarity` VARCHAR(50) NOT NULL,
  `elixir_cost` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`card_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CLASHROYALE`.`decks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CLASHROYALE`.`decks` ;

CREATE TABLE IF NOT EXISTS `CLASHROYALE`.`decks` (
  `deck_code` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  `elixir_cost` DECIMAL(2,1) NULL DEFAULT NULL,
  `created_at` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`deck_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CLASHROYALE`.`deck_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CLASHROYALE`.`deck_cards` ;

CREATE TABLE IF NOT EXISTS `CLASHROYALE`.`deck_cards` (
  `deck_code` INT(11) NOT NULL,
  `card_number` INT(11) NOT NULL,
  `index_card` INT(11) NOT NULL,
  PRIMARY KEY (`deck_code`, `index_card`),
  INDEX `card_number` (`card_number` ASC),
  CONSTRAINT `DECK_cards_ibfk_1`
    FOREIGN KEY (`deck_code`)
    REFERENCES `CLASHROYALE`.`decks` (`deck_code`),
  CONSTRAINT `DECK_cards_ibfk_2`
    FOREIGN KEY (`card_number`)
    REFERENCES `CLASHROYALE`.`cards` (`card_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
