USE CLASHROYALE;

INSERT INTO cards(name, elixir_cost, rarity) VALUES
('Archers', 3, 'Common'),
('Baby Dragon', 4, 'Epic'),
('Balloon', 5, 'Epic'),
('Bandit', 3, 'Legendary'),
('Barbarians', 5, 'Common'),
('Bats', 2, 'Common'),
('Battle Ram', 4, 'Rare'),
('Bomber', 3, 'Common'),
('Bowler', 5, 'Epic'),
('Cannon Cart', 5, 'Epic'),
('Dark Prince', 4, 'Epic'),
('Dart Goblin', 3, 'Rare'),
('Electro Dragon', 5, 'Epic'),
('Electro Wizard', 4, 'Legendary'),
('Elite Barbarians', 6, 'Common'),
('Elixir Golem', 3, 'Rare'),
('Executioner', 5, 'Epic'),
('Fire Spirits', 2, 'Common'),
('Fisherman', 3, 'Legendary'),
('Flying Machine', 4, 'Rare'),
('Giant', 5, 'Rare'),
('Giant Skeleton', 6, 'Epic'),
('Goblin Gang', 3, 'Common'),
('Goblin Giant', 6, 'Epic'),
('Goblins', 2, 'Common'),
('Golem', 8, 'Epic'),
('Guards', 3, 'Epic'),
('Hog Rider', 4, 'Rare'),
('Hunter', 4, 'Epic'),
('Ice Golem', 2, 'Rare'),
('Ice Spirit', 1, 'Common'),
('Ice Wizard', 3, 'Legendary'),
('Inferno Dragon', 4, 'Legendary'),
('Knight', 3, 'Common'),
('Lava Hound', 7, 'Legendary'),
('Lumberjack', 4, 'Legendary'),
('Magic Archer', 4, 'Legendary'),
('Mega Knight', 7, 'Legendary'),
('Mega Minion', 3, 'Rare'),
('Mini P.E.K.K.A.', 4, 'Rare'),
('Miner', 3, 'Legendary'),
('Minions', 3, 'Common'),
('Minion Horde', 5, 'Common'),
('Musketeer', 4, 'Rare'),
('Night Witch', 4, 'Epic'),
('P.E.K.K.A.', 7, 'Epic'),
('Prince', 5, 'Epic'),
('Princess', 3, 'Legendary'),
('Ram Rider', 5, 'Legendary'),
('Rascals', 5, 'Common'),
('Royal Ghost', 3, 'Legendary'),
('Royal Giant', 6, 'Common'),
('Royal Hogs', 5, 'Rare'),
('Royal Recruits', 7, 'Common'),
('Skeletons', 1, 'Common'),
('Skeleton Army', 3, 'Epic'),
('Skeleton Barrel', 3, 'Common'),
('Sparky', 6, 'Legendary'),
('Spear Goblins', 2, 'Common'),
('Three Musketeers', 9, 'Rare'),
('Valkyrie', 4, 'Rare'),
('Wall Breakers', 2, 'Epic'),
('Witch', 5, 'Epic'),
('Wizard', 5, 'Rare'),
('Zappies', 4, 'Rare'),
('Bomb Tower', 4, 'Rare'),
('Cannon', 3, 'Common'),
('Inferno Tower', 5, 'Rare'),
('Mortar', 4, 'Common'),
('Tesla', 4, 'Common'),
('X-Bow', 6, 'Epic'),
('Barbarian Hut', 7, 'Rare'),
('Elixir Collector', 6, 'Rare'),
('Furnace', 4, 'Rare'),
('Goblin Hut', 3, 'Epic'),
('Goblin Cage', 4, 'Rare'),
('Tombstone', 3, 'Rare'),
('Arrows', 3, 'Common'),
('Barbarian Barrel', 2, 'Epic'),
('Goblin Barrel', 3, 'Epic'),
('Earthquake', 3, 'Rare'),
('Fireball', 4, 'Rare'),
('Freeze', 4, 'Epic'),
('Giant Snowball', 2, 'Common'),
('Lightning', 6, 'Epic'),
('Poison', 4, 'Epic'),
('Rocket', 6, 'Rare'),
('The Log', 2, 'Legendary'),
('Tornado', 3, 'Epic'),
('Zap', 2, 'Common'),
('Clone', 3, 'Epic'),
('Heal', 1, 'Rare'),
('Mirror', 3, 'Epic'),
('Rage', 2, 'Epic'),
('Graveyard', 5, 'Legendary');