USE CLASHROYALE;

INSERT INTO cartas(nome, custo, raridade) VALUES
('Cura', 1, 'Rara'),
('Espelho', 3, 'Épica'),
('Espírito de Gelo', 1, 'Comum'),
('Esqueletos', 1, 'Comum'),
('Bola de Neve', 2, 'Comum'),
('Destruidores de Muros', 2, 'Épica'),
('Morcegos', 2, 'Comum'),
('Barril de Bárbaro', 2, 'Épica'),
('Fúria', 2, 'Épica'),
('Espíritos de Fogo', 2, 'Comum'),
('Goblins', 2, 'Comum'),
('Goblins Lanceiros', 2, 'Comum'),
('Terremoto', 3, 'Rara'),
('Servos', 3, 'Comum'),
('Arqueiras', 3, 'Comum'),
('Clone', 3, 'Épica'),
('Barril de Esqueletos', 3, 'Comum'),
('Tornado', 3, 'Épica'),
('Mago de Gelo', 3, 'Lendária'),
('Canhão', 3, 'Comum'),
('Guardas', 3, 'Épica'),
('Fantasma Real', 3, 'Lendária'),
('Lápide', 3, 'Rara'),
('Bandida', 3, 'Lendária'),
('Barril de Goblin', 3, 'Épica'),
('Bombardeiro', 3, 'Comum'),
('Mineiro', 3, 'Lendária'),
('Gangue de Goblins', 3, 'Comum'),
('Flechas', 3, 'Comum'),
('Goblin com Dardo', 3, 'Rara'),
('Megasservo', 3, 'Rara'),
('Golem de Elixir', 3, 'Rara'),
('Dragão Infernal', 4, 'Lendária'),
('Aríete de Batalha', 4, 'Rara'),
('Lenhador', 4, 'Lendária'),
('Valquíria', 4, 'Rara'),
('Bola de Fogo', 4, 'Rara'),
('Caçador', 4, 'Épica'),
('Jaula de Goblin', 4, 'Rara'),
('Gelo', 4, 'Épica'),
('Fornalha', 4, 'Rara'),
('Mosqueteira', 4, 'Rara'),
('Príncipe das Trevas', 4, 'Épica'),
('Tesla', 4, 'Comum'),
('Eletrocutadores', 4, 'Rara'),
('Torre de Bombas', 4, 'Rara'),
('Morteiro', 4, 'Comum'),
('Veneno', 4, 'Épica'),
('Corredor', 4, 'Rara'),
('Máquina Voadora', 4, 'Rara'),
('Bebê Dragão', 4, 'Épica'),
('Mini P.E.K.K.A', 4, 'Rara'),
('Bruxa', 5, 'Épica'),
('Dragão Elétrico', 5, 'Épica'),
('Porcos Reais', 5, 'Rara'),
('Cabana de Goblins', 5, 'Rara'),
('Carrinho de Canhão', 5, 'Épica'),
('Torre Inferno', 5, 'Rara'),
('Patifes', 5, 'Comum'),
('Balão', 5, 'Épica'),
('Executor', 5, 'Épica'),
('Lançador', 5, 'Épica'),
('Gigante', 5, 'Rara'),
('Cemitério', 5, 'Lendária'),
('Horda de Servos', 5, 'Comum'),
('Príncipe', 5, 'Épica'),
('Bárbaros', 5, 'Comum'),
('Domadora de Carneiro', 5, 'Lendária'),
('Goblin Gigante', 6, 'Épica'),
('Coletor de Elixir', 6, 'Rara'),
('X-Besta', 6, 'Épica'),
('Gigante Real', 6, 'Comum'),
('Esqueleto Gigante', 6, 'Épica'),
('Megacavaleiro', 7, 'Lendária'),
('Cabana de Bárbaros', 7, 'Rara'),
('Recrutas Reais', 7, 'Comum'),
('Lava Hound', 7, 'Lendária'),
('Golem', 8, 'Épica'),
('Três Mosqueteiras', 9, 'Rara'),
('Pescador', 3, 'Lendária'),
('Bruxa Sombria', 4, 'Épica'),
('Arqueiro Mágico', 4, 'Lendária'),
('P.E.K.K.A', 7, 'Épica'),
('Mago', 5, 'Rara'),
('Cavaleiro', 3, 'Comum'),
('O Tronco', 2, 'Lendária'),
('Exército de Esqueletos', 3, 'Épica'),
('Princesa', 3, 'Lendária'),
('Mago Elétrico', 4, 'Lendária'),
('Zap', 2, 'Comum');


INSERT INTO decks(nome, descricao, custo, data_criacao) VALUES
('Deck 1', 'Teste A', 4.7, '2019-12-15'),
('Deck 2', 'Teste b', 4.7, '2019-12-15'),
('Deck 3', 'Teste c', 4.7, '2019-12-15');

INSERT INTO deck_cartas (codigo_deck, numero_carta, index_carta) VALUES
(1, 1, 0),
(1, 2, 1),
(1, 3, 2),
(1, 4, 3),
(2, 5, 4),
(2, 6, 5),
(3, 7, 0);